<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="QCDeployment" nsURI="http://quantum-computing/deployment/1.0"
    nsPrefix="QCDeployment">
  <eClassifiers xsi:type="ecore:EClass" name="Credential" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Token" eSuperTypes="#//Credential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicAuth" eSuperTypes="#//Credential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" upperBound="-1"
        eType="#//Credential" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithmexecution" lowerBound="1"
        upperBound="-1" eType="#//AlgorithmExecution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmExecution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithmexecution" lowerBound="1"
        eType="ecore:EClass ../../jku.se.quantum.computing.mm/model/QuantumComputing.ecore#//QuantumAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="ecore:EClass ../../jku.se.social.network.mm/model/SocialNetwork.ecore#//SocialNetwork"/>
  </eClassifiers>
</ecore:EPackage>
